baseURL = "https://nighttime.coffee"
languageCode = "en-us"
title = "Night Time Coffee"
theme="ezhil"

# Enable syntax highlighting.
pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
	# Blog subtitle which appears below blog title. Supports markdown.
	subtitle = "Clearing out my backlog of projects"
	# Number of posts to show in recent posts list (Optional). Defaults to 10.
	recentPostsCount = 25
	# Content types which are excluded from recent posts and archive page (Optional). Defaults to ["page"]
	excludedTypes = ["page"]
	# If social media links are enabled then enable this to fetch icons from CDN instead of hosted on your site.
	featherIconsCDN = true
	# Dark Mode
	mode = "dark"

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Learn"
url = "/learn"
weight = 4

[[menu.main]]
name = "Tag"
url = "/tag"
weight = 5

# Social media links which shows up on site header.
# Uses feather icons for icons. You can [search icon names from here](https://feathericons.com/).
[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/nighttime-coffee/"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/mjharmon"

# Enable tags.
[taxonomies]
   tag = "tags"
